export const DANG_NHAP_ACTION = 'DANG_NHAP_ACTION';
export const SET_THONG_TIN_NGUOI_DUNG = 'SET_THONG_TIN_NGUOI_DUNG';

export const DANG_KY = 'DANG_KY';
export const SET_LIST_USER = 'SET_LIST_USER';
export const TIM_KIEM_USER = 'TIM_KIEM_USER';
export const DANH_SACH_LOAI_NGUOI_DUNG = 'DANH_SACH_LOAI_NGUOI_DUNG';

